CREATE TABLE
  IF NOT EXISTS serviceFee (
    active INTEGER DEFAULT 1,
    createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
    updatedAt TEXT DEFAULT CURRENT_TIMESTAMP
  );

CREATE TRIGGER IF NOT EXISTS serviceFeeUpdated AFTER
UPDATE ON serviceFee FOR EACH ROW BEGIN
UPDATE serviceFee
SET
  updated_at = CURRENT_TIMESTAMP
WHERE
  id = OLD.id;

END;