id:
  autoIncrement: true
  order: 0
  primaryKey: true
  type: int

memberId:
  hidden: true
  many: true
  order: 1
  referenceTable: member
  type: int

loanPurpose:
  order: 2
  type: text

loanAmount:
  order: 3
  type: real

repaymentPeriodInMonths:
  order: 4
  type: int

loanType:
  options:
    - Personal
    - Business
    - Agricultural
    - Emergency
  order: 5
  type: text
