cacheQueries:
  description: member.memberLoan.0.memberLoanSecurity.0.description
  id: member.memberLoan.0.memberLoanSecurity.0.id
  memberLoanId: member.memberLoan.0.memberLoanSecurity.0.memberLoanId
  serialNumber: member.memberLoan.0.memberLoanSecurity.0.serialNumber
  value: member.memberLoan.0.memberLoanSecurity.0.value
enterDescription:
  inputIdentifier: description
  nextScreen: enterValue
  order: 1
  text:
    en: Description
  type: inputScreen
enterId:
  hidden: true
  inputIdentifier: id
  type: hiddenField
enterMemberLoanId:
  hidden: true
  inputIdentifier: memberLoanId
  type: hiddenField
enterSerialNumber:
  inputIdentifier: serialNumber
  nextScreen: formSummary
  order: 3
  text:
    en: Serial Number
  type: inputScreen
enterValue:
  inputIdentifier: value
  nextScreen: enterSerialNumber
  order: 2
  text:
    en: Value
  type: inputScreen
  validationRule: ^\d+\.*\d*$
formSummary:
  type: quitScreen
initialScreen: enterDescription
model: memberLoanSecurity
parentIds:
  - memberLoanId
rootQuery: member.memberLoan.0.memberLoanSecurity.0
