cacheQueries:
  description1: member.memberLoanApplication.0.memberLoan.0.memberLoanSecurity.0.description
  id1: member.memberLoanApplication.0.memberLoan.0.memberLoanSecurity.0.id
  memberLoanId1: member.memberLoanApplication.0.memberLoan.0.memberLoanSecurity.0.memberLoanId
  serialNumber1: member.memberLoanApplication.0.memberLoan.0.memberLoanSecurity.0.serialNumber
  value1: member.memberLoanApplication.0.memberLoan.0.memberLoanSecurity.0.value
enterDescription1:
  inputIdentifier: description1
  nextScreen: enterValue1
  order: 1
  text:
    en: Description
  type: inputScreen
enterId1:
  hidden: true
  inputIdentifier: id1
  type: hiddenField
enterMemberLoanId1:
  hidden: true
  inputIdentifier: memberLoanId1
  type: hiddenField
enterSerialNumber1:
  inputIdentifier: serialNumber1
  nextScreen: formSummary
  order: 3
  text:
    en: Serial Number
  type: inputScreen
enterValue1:
  inputIdentifier: value1
  nextScreen: enterSerialNumber1
  order: 2
  text:
    en: Value
  type: inputScreen
  validationRule: ^\d+\.*\d*$
formSummary:
  type: quitScreen
initialScreen: enterDescription1
model: memberLoanSecurity
parentIds:
  - memberLoanId
rootQuery: member.memberLoanApplication.0.memberLoan.0.memberLoanSecurity.0
