id:
  autoIncrement: true
  order: 0
  primaryKey: true
  type: int

memberLoanId:
  order: 1
  referenceTable: memberLoan
  type: int

description:
  order: 2
  type: text

value:
  order: 3
  type: real

serialNumber:
  order: 4
  type: text
